### Verbo GET – listar
GET http://localhost:8000/funcionario/0 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/4 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "matricula" : "01923874656",
    "cpf" : "49988234567",
    "telefone" : "bolinhas",
    "matricula" : "12345",
    "grupo" : 1,
    "senha" : "dasfdfsdf"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "matricula" : "01923874656",
    "cpf" : "49988234567",
    "telefone" : "bolinhas",
    "matricula" : "12345",
    "grupo" : 1,
    "senha" : "dasfdfsdf"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1