### Verbo GET – listar
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "fsdfsdsdffsd",
    "cpf" : "747474",
    "senha" : "bolinhas",
    "matricula" : "01923874656",
    "telefone" : "bolinhas",
    "grupo" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/3 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc EDITADO",
    "cpf" : "9999998",
    "senha" : "saasasas",
    "matricula" : "01923874656",
    "telefone" : "33333",
    "grupo" : 1
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
