### Verbo GET – listar
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar - com autenticacao
curl -x 'GET' \
    'http://localhost:8000/produto/' \
    -H 'Accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "teste",
    "descricao" : "frfrfr bruxo",
    "foto" : "" ,
    "valor_unitario" : "43434.44"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/4 HTTP/1.1
content-type: application/json

{
    "nome" : "teste editado",
    "descricao" : "produto",
    "foto" : "" ,
    "valor_unitario" : "43434.55"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1