### Verbo GET – listar
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar - com autenticacao
curl -x 'GET' \
    'http://localhost:8000/cliente/' \
    -H 'Accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "ffefererer",
    "cpf" : "4747474",
    "telefone" : "55555555",
    "compra_fiado" : "258",
    "dia_fiado" : "25",
    "senha" : "abc"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc EDITADO ",
    "cpf" : "01923874656",
    "telefone" : "49988234567",
    "compra_fiado" : "150",
    "dia_fiado" : "12",
    "senha" : "abc"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1

